export const journalPrompts: string[] = [
	'What is something you are grateful for today?',
	'Who in your life brings you the most joy and why?',
	'What is a recent accomplishment, big or small, that you’re proud of?',
	'What is a challenge you’ve faced recently that you’ve learned from?',
	'What’s something you often take for granted but are truly grateful for?',
	'What is one thing about your health that you’re thankful for?',
	'What is one of your favorite memories that makes you feel thankful?',
	'What are three things you appreciate about your home or living space?',
	'What is a skill or talent you’re grateful to have?',
	'Who is someone who has supported you in your life, and how have they helped?',
	'What is something you’ve done recently that you’re grateful for?',
	'What is a simple pleasure in life that you’re thankful for?',
	'What part of your daily routine brings you the most peace or joy?',
	'What’s something in nature that makes you feel connected and grateful?',
	'What is a meaningful gift you’ve received that still holds significance for you?',
	'What’s a recent kind gesture someone has done for you?',
	'What are you grateful for in your career or current job?',
	'What’s something you’ve learned that you are thankful for?',
	'What is one thing you’re grateful for about the person you’ve become?',
	'What’s something that brings you comfort or happiness in tough times?',
	'What is a pivotal moment from your past that shaped who you are today?',
	'What is something you used to believe that you no longer believe?',
	"What is a mistake you've made in the past that taught you a valuable lesson?",
	'What is a past accomplishment you are most proud of?',
	'What is a decision you made in the past that you are grateful for?',
	'Who has been a significant influence in your life, and how did they shape you?',
	'What is something you’ve learned from a challenging situation in your past?',
	'What childhood memory still brings you joy when you think of it?',
	'What is a place from your past that holds special meaning to you?',
	'What is a regret from your past, and what did you learn from it?',
	'What event or experience in your past helped you grow as a person?',
	'How has your relationship with yourself evolved over the years?',
	'What is a fear you once had that you have now overcome?',
	'What were your dreams or goals when you were younger, and how have they changed?',
	'What is a habit or routine you’ve carried from the past that has been beneficial?',
	'What is something you are grateful for from a difficult time in your past?',
	'What was the best advice you received during a challenging period in your life?',
	'What is a favorite lesson you learned from your family or upbringing?',
	'What is something you wish you had known earlier in life?',
	'How do you think your past experiences have influenced your current values and beliefs?',
];
