export const journalPrompts: string[] = [
	'What is something you are grateful for today?',
	'Who in your life brings you the most joy and why?',
	'What is a recent accomplishment, big or small, that you’re proud of?',
	'What is a challenge you’ve faced recently that you’ve learned from?',
	'What’s something you often take for granted but are truly grateful for?',
	'What is one thing about your health that you’re thankful for?',
	'What is one of your favorite memories that makes you feel thankful?',
	'What are three things you appreciate about your home or living space?',
	'What is a skill or talent you’re grateful to have?',
	'Who is someone who has supported you in your life, and how have they helped?',
	'What is something you’ve done recently that you’re grateful for?',
	'What is a simple pleasure in life that you’re thankful for?',
	'What part of your daily routine brings you the most peace or joy?',
	'What’s something in nature that makes you feel connected and grateful?',
	'What is a meaningful gift you’ve received that still holds significance for you?',
	'What’s a recent kind gesture someone has done for you?',
	'What are you grateful for in your career or current job?',
	'What’s something you’ve learned that you are thankful for?',
	'What is one thing you’re grateful for about the person you’ve become?',
	'What’s something that brings you comfort or happiness in tough times?',
];
